# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
S3_BUCKET_NAME: itsybikini
AWS_ACCESS_KEY_ID: AKIAJP4KD5CHC6AXJOHA
AWS_SECRET_ACCESS_KEY: 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
